// dreamspos_v2.0.6/react/template/src/feature-module/usermanagement/users.jsx
import React, { useState } from 'react'
import { OverlayTrigger, Tooltip } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import ImageWithBasePath from '../../core/img/imagewithbasebath';
import { ChevronUp, RotateCcw } from 'feather-icons-react/build/IconComponents';
import { setToogleHeader } from '../../core/redux/action';
import { useDispatch, useSelector } from 'react-redux';
import { Filter, PlusCircle, Sliders, StopCircle, User, Zap } from 'react-feather';
import Select from 'react-select';
import withReactContent from 'sweetalert2-react-content';
import Swal from 'sweetalert2';
import Table from '../../core/pagination/datatable'
import AddUsers from '../../core/modals/usermanagement/addusers';
import EditUser from '../../core/modals/usermanagement/edituser';


const Users = () => {

    const oldandlatestvalue = [
        { value: 'date', label: 'Sort by Date' },
        { value: 'newest', label: 'Newest' },
        { value: 'oldest', label: 'Oldest' },
    ];
    const users = [
        { value: 'Choose Name', label: 'Choose Name' },
        { value: 'Lilly', label: 'Lilly' },
        { value: 'Benjamin', label: 'Benjamin' },
    ];
    const status = [
        { value: 'Choose Name', label: 'Choose Status' },
        { value: 'Active', label: 'Active' },
        { value: 'InActive', label: 'InActive' },
    ];
    const role = [
        { value: 'Choose Role', label: 'Choose Role' },
        { value: 'AcStore Keeper', label: 'Store Keeper' },
        { value: 'Salesman', label: 'Salesman' },
    ];


    const dispatch = useDispatch();
    const data = useSelector((state) => state.toggle_header);
    const dataSource = useSelector((state) => state.userlist_data);
    const [isFilterVisible, setIsFilterVisible] = useState(false);
    const toggleFilterVisibility = () => {
        setIsFilterVisible((prevVisibility) => !prevVisibility);
    };

    const renderTooltip = (props) => (
        <Tooltip id="pdf-tooltip" {...props}>
            Pdf
        </Tooltip>
    );
    const renderExcelTooltip = (props) => (
        <Tooltip id="excel-tooltip" {...props}>
            Excel
        </Tooltip>
    );
    const renderPrinterTooltip = (props) => (
        <Tooltip id="printer-tooltip" {...props}>
            Printer
        </Tooltip>
    );
    const renderRefreshTooltip = (props) => (
        <Tooltip id="refresh-tooltip" {...props}>
            Refresh
        </Tooltip>
    );
    const renderCollapseTooltip = (props) => (
        <Tooltip id="refresh-tooltip" {...props}>
            Collapse
        </Tooltip>
    )

    const columns = [

        {
            title: "User Name",
            dataIndex: "username",
            render: (text, record) => (
                <span className="userimgname">
                    <Link to="#" className="userslist-img bg-img">
                        <ImageWithBasePath alt="" src={record.img} />
                    </Link>
                    <div>
                    <Link to="#">{text}</Link>
                    </div>
                </span>
            ),
            sorter: (a, b) => a.username.length - b.username.length,
        },

        {
            title: "Phone",
            dataIndex: "phone",
            sorter: (a, b) => a.phone.length - b.phone.length,
        },
        {
            title: "Email",
            dataIndex: "email",
            sorter: (a, b) => a.email.length - b.email.length,
        },
        {
            title: "Role",
            dataIndex: "role",
            sorter: (a, b) => a.role.length - b.role.length,
        },
        {
            title: "Created On",
            dataIndex: "createdon",
            sorter: (a, b) => a.createdon.length - b.createdon.length,
        },
        {
            title: "Status",
            dataIndex: "status",
            render: (text) => (
                <div>
                  {text === "Active" && (
                    <span className="badge badge-linesuccess">{text}</span>
                  )}
                  {text === "Inactive" && (
                    <span className="badge badge-linedanger">{text}</span>
                  )}
                  
                </div>
              ),
            sorter: (a, b) => a.status.length - b.status.length,
        },
        {
            title: 'Actions',
            dataIndex: 'actions',
            key: 'actions',
            render: () => (
                <td className="action-table-data">
                    <div className="edit-delete-action">
                        
                        <Link className="me-2 p-2" to="#">
                            <i data-feather="eye" className="feather feather-eye action-eye"></i>
                        </Link>
                        <Link className="me-2 p-2" to="#" data-bs-toggle="modal" data-bs-target="#edit-units">
                            <i data-feather="edit" className="feather-edit"></i>
                        </Link>
                        <Link className="confirm-text p-2" to="#"  >
                            <i data-feather="trash-2" className="feather-trash-2" onClick={showConfirmationAlert}></i>
                        </Link>
                    </div>
                </td>
            )
        },
    ]
    const MySwal = withReactContent(Swal);

    const showConfirmationAlert = () => {
        MySwal.fire({
            title: 'Are you sure?',
            text: 'You won\'t be able to revert this!',
            showCancelButton: true,
            confirmButtonColor: '#00ff00',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonColor: '#ff0000',
            cancelButtonText: 'Cancel',
        }).then((result) => {
            if (result.isConfirmed) {

                MySwal.fire({
                    title: 'Deleted!',
                    text: 'Your file has been deleted.',
                    className: "btn btn-success",
                    confirmButtonText: 'OK',
                    customClass: {
                        confirmButton: 'btn btn-success',
                    },
                });
            } else {
                MySwal.close();
            }

        });
    };
    return (
        <div>
            <div className="page-wrapper">
                <div className="content">
                    <div className="page-header">
                        <div className="add-item d-flex">
                            <div className="page-title">
                                <h4>User List</h4>
                                <h6>Manage Your Users</h6>
                            </div>
                        </div>
                        <ul className="table-top-head">
                            <li>
                                <OverlayTrigger placement="top" overlay={renderTooltip}>
                                    <Link>
                                        <ImageWithBasePath src="assets/img/icons/pdf.svg" alt="img" />
                                    </Link>
                                </OverlayTrigger>
                            </li>
                            <li>
                                <OverlayTrigger placement="top" overlay={renderExcelTooltip}>
                                    <Link data-bs-toggle="tooltip" data-bs-placement="top">
                                        <ImageWithBasePath src="assets/img/icons/excel.svg" alt="img" />
                                    </Link>
                                </OverlayTrigger>
                            </li>
                            <li>
                                <OverlayTrigger placement="top" overlay={renderPrinterTooltip}>

                                    <Link data-bs-toggle="tooltip" data-bs-placement="top">
                                        <i data-feather="printer" className="feather-printer" />
                                    </Link>
                                </OverlayTrigger>
                            </li>
                            <li>
                                <OverlayTrigger placement="top" overlay={renderRefreshTooltip}>

                                    <Link data-bs-toggle="tooltip" data-bs-placement="top">
                                        <RotateCcw />
                                    </Link>
                                </OverlayTrigger>
                            </li>
                            <li>
                                <OverlayTrigger placement="top" overlay={renderCollapseTooltip}>

                                    <Link
                                        data-bs-toggle="tooltip"
                                        data-bs-placement="top"
                                        id="collapse-header"
                                        className={data ? "active" : ""}
                                        onClick={() => { dispatch(setToogleHeader(!data)) }}
                                    >
                                        <ChevronUp />
                                    </Link>
                                </OverlayTrigger>
                            </li>
                        </ul>
                        <div className="page-btn">
                            <a
                                to="#"
                                className="btn btn-added"
                                data-bs-toggle="modal"
                                data-bs-target="#add-units"
                            >
                                <PlusCircle className="me-2" />
                                Add New User
                            </a>
                        </div>
                    </div>
                    {/* /product list */}
                    <div className="card table-list-card">
                        <div className="card-body">
                            <div className="table-top">
                                <div className="search-set">
                                    <div className="search-input">
                                        <input
                                            type="text"
                                            placeholder="Search"
                                            className="form-control form-control-sm formsearch"
                                        />
                                        <Link to className="btn btn-searchset">
                                            <i data-feather="search" className="feather-search" />
                                        </Link>
                                    </div>
                                </div>
                                <div className="search-path">
                                    <Link className={`btn btn-filter ${isFilterVisible ? "setclose" : ""}`} id="filter_search">
                                        <Filter
                                            className="filter-icon"
                                            onClick={toggleFilterVisibility}
                                        />
                                        <span onClick={toggleFilterVisibility}>
                                            <ImageWithBasePath src="assets/img/icons/closes.svg" alt="img" />
                                        </span>
                                    </Link>
                                </div>
                                <div className="form-sort">
                                    <Sliders className="info-img" />
                                    <Select
                                        className="select"
                                        options={oldandlatestvalue}
                                        placeholder="Newest"
                                    />
                                </div>
                            </div>
                            {/* /Filter */}
                            <div
                                className={`card${isFilterVisible ? ' visible' : ''}`}
                                id="filter_inputs"
                                style={{ display: isFilterVisible ? 'block' : 'none' }}
                            >
                                <div className="card-body pb-0">
                                    <div className="row">
                                        <div className="col-lg-3 col-sm-6 col-12">
                                            <div className="input-blocks">
                                                <User className="info-img" />

                                                <Select
                                                    className="select"
                                                    options={users}
                                                    placeholder="Newest"
                                                />
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-sm-6 col-12">
                                            <div className="input-blocks">
                                                <StopCircle className="info-img" />

                                                <Select
                                                    className="select"
                                                    options={status}
                                                    placeholder="Choose Status"
                                                />
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-sm-6 col-12">
                                            <div className="input-blocks">
                                                <Zap className="info-img" />

                                                <Select
                                                    className="select"
                                                    options={role}
                                                    placeholder="Choose Role"
                                                />
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-sm-6 col-12">
                                            <div className="input-blocks">
                                                <a className="btn btn-filters ms-auto">
                                                    {" "}
                                                    <i data-feather="search" className="feather-search" />{" "}
                                                    Search{" "}
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/* /Filter */}
                            <div className="table-responsive">
                                <Table columns={columns} dataSource={dataSource} />

                            </div>
                        </div>
                    </div>
                    {/* /product list */}
                </div>
            </div>
        <AddUsers/>
        <EditUser/>
        </div>
    )
}

export default Users

// dreamspos_v2.0.6/angular/template/src/app/core-component/user-management/users/users.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import {
  DataService,
  pageSelection,
  apiResultFormat,
  SidebarService,
} from 'src/app/core/core.index';
import { routes } from 'src/app/core/helpers/routes';
import { users } from 'src/app/shared/model/page.model';
import { PaginationService, tablePageSize } from 'src/app/shared/shared.index';
import Swal from 'sweetalert2';
@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrl: './users.component.scss',
})
export class UsersComponent {
  initChecked = false;
  selectedValue1 = '';
  selectedValue2 = '';
  selectedValue3 = '';
  selectedValue4 = '';
  selectedValue5 = '';
  selectedValue6 = '';
  selectedValue7 = '';

  public routes = routes;
  // pagination variables
  public tableData: Array<users> = [];
  public pageSize = 10;
  public serialNumberArray: Array<number> = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<users>;
  public searchDataValue = '';
  //** / pagination variables

  constructor(
    private data: DataService,
    private pagination: PaginationService,
    private router: Router,
    private sidebar: SidebarService
  ) {
    this.data.getDataTable().subscribe((apiRes: apiResultFormat) => {
      this.totalData = apiRes.totalData;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.users) {
          this.getTableData({ skip: res.skip, limit: this.totalData  });
          this.pageSize = res.pageSize;
        }
      });
    });
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getUsers().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: users, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.sNo = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<users>(this.tableData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }

  public searchData(value: string): void {
    this.dataSource.filter = value.trim().toLowerCase();
    this.tableData = this.dataSource.filteredData;
  }
  isCollapsed: boolean = false;
  toggleCollapse() {
    this.sidebar.toggleCollapse();
    this.isCollapsed = !this.isCollapsed;
  }
  public filter = false;
  openFilter() {
    this.filter = !this.filter;
  }
  confirmColor() {
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: ' btn btn-success',
        cancelButton: 'me-2 btn btn-danger',
      },
      buttonsStyling: false,
    });

    swalWithBootstrapButtons
      .fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        confirmButtonText: 'Yes, delete it!',
        showCancelButton: true,
        cancelButtonText: 'Cancel',
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          swalWithBootstrapButtons.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          );
        } else if (result.dismiss === Swal.DismissReason.cancel) {
          swalWithBootstrapButtons.fire(
            'Cancelled',
            'Your imaginary file is safe :)',
            'error'
          );
        }
      });
  }

  public password : boolean[] = [false];

  public togglePassword(index: number){
    this.password[index] = !this.password[index]
  }
  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
}

<div class="page-header">
  <div class="add-item d-flex">
    <div class="page-title">
      <h4>User List</h4>
      <h6>Manage Your Users</h6>
    </div>
  </div>
  <ul class="table-top-head">
    <li>
      <a data-bs-toggle="tooltip" data-bs-placement="top" matTooltip="Pdf" matTooltipPosition="above"><img
      src="assets/img/icons/pdf.svg" alt="img"></a>
    </li>
    <li>
      <a data-bs-toggle="tooltip" data-bs-placement="top" matTooltip="Excel" matTooltipPosition="above"><img
      src="assets/img/icons/excel.svg" alt="img"></a>
    </li>
    <li>
      <a data-bs-toggle="tooltip" data-bs-placement="top" matTooltip="Print" matTooltipPosition="above"><i
      class="feather icon-printer feather-rotate-ccw"></i></a>
    </li>
    <li>
      <a data-bs-toggle="tooltip" data-bs-placement="top" matTooltip="Refresh" matTooltipPosition="above"><i
      class="feather icon-rotate-ccw feather-rotate-ccw"></i></a>
    </li>
    <li>
      <a (click)="toggleCollapse()" data-bs-toggle="tooltip" data-bs-placement="top" matTooltip="Collapse"
        matTooltipPosition="above" id="collapse-header"> @if (!isCollapsed) {
        <i class="feather icon-chevron-up feather-chevron-up"></i>
      }
      @if (isCollapsed) {
        <i class="feather icon-chevron-down feather-chevron-down"></i>
      }</a>
    </li>
  </ul>
  <div class="page-btn">
    <a href="javascript:void(0);" class="btn btn-added" data-bs-toggle="modal" data-bs-target="#add-units"><i
    class="feather icon-plus-circle me-2"></i>Add New User</a>
  </div>
</div>

<!-- /product list -->
<div class="card table-list-card">
  <div class="card-body">
    <div class="table-top">
      <div class="search-set">
        <div class="search-input">
          <a href="javascript:void(0);" class="btn btn-searchset"><i class="feather icon-search feather-search"></i></a>
          <div class="dataTables_filter">
            <label>
              <input [(ngModel)]="searchDataValue" [ngModelOptions]="{standalone: true}" (ngModelChange)="searchData(searchDataValue)" type="search"
                class="form-control" placeholder="Search..." />
              </label>
            </div>
          </div>
        </div>
        <div class="search-path">
          <div class="d-flex align-items-center">
            <a class="btn btn-filter" id="filter_search" (click)="openFilter()" [ngClass]="{'setclose': filter === true}">
              <i class="feather icon-filter filter-icon"></i>
              <span><img src="assets/img/icons/closes.svg" alt="img"></span>
            </a>
          </div>
        </div>
        <div class="form-sort">
          <i class="feather icon-sliders info-img"></i>
          <mat-select [(ngModel)]="selectedValue2" [ngModelOptions]="{standalone: true}" class="space-select select"
            placeholder="Sort by Date">
            <mat-option value="Sort by Date">Sort by Date</mat-option>
            <mat-option value="Newest">Newest</mat-option>
            <mat-option value="Oldest">Oldest</mat-option>
          </mat-select>
        </div>
      </div>
      <!-- /Filter -->
      <div class="card" id="filter_inputs" [ngClass]="{'d-block': filter, 'd-none': !filter}">
        <div class="card-body pb-0">
          <div class="row">
            <div class="col-lg-3 col-sm-6 col-12">
              <div class="input-blocks">
                <i class="feather icon-user info-img"></i>
                <mat-select [(ngModel)]="selectedValue3" [ngModelOptions]="{standalone: true}" class="space-select select"
                  placeholder="Choose Name">
                  <mat-option value="Choose Name">Choose Name</mat-option>
                  <mat-option value="Lilly">Lilly</mat-option>
                  <mat-option value="Benjamin">Benjamin</mat-option>
                </mat-select>
              </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-12">
              <div class="input-blocks">
                <i class="feather icon-stop-circle info-img"></i>
                <mat-select [(ngModel)]="selectedValue4" [ngModelOptions]="{standalone: true}" class="space-select select"
                  placeholder="Choose Status">
                  <mat-option value="Choose Status">Choose Status</mat-option>
                  <mat-option value="Active">Active</mat-option>
                  <mat-option value="Inactive">Inactive</mat-option>
                </mat-select>
              </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-12">
              <div class="input-blocks">
                <i class="feather icon-zap info-img"></i>
                <mat-select [(ngModel)]="selectedValue5" [ngModelOptions]="{standalone: true}" class="space-select select"
                  placeholder="Choose Role">
                  <mat-option value="Choose Role">Choose Role</mat-option>
                  <mat-option value="Store Keeper">Store Keeper</mat-option>
                  <mat-option value="Salesman">Salesman</mat-option>
                </mat-select>
              </div>
            </div>
            <div class="col-lg-3 col-sm-6 col-12">
              <div class="input-blocks">
                <a class="btn btn-filters ms-auto"> <i class="feather icon-search feather-search"></i>
              Search </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Filter -->
    <div class="table-responsive">
      <table matSort (matSortChange)="sortData($event)" class="table datanew">
        <thead>
          <tr>
            <th class="no-sort">
                <label class="checkboxs"  (click)="selectAll(initChecked)">
                  <input type="checkbox" id="select-all" [(ngModel)]="initChecked" >
                  <span class="checkmarks"></span>
                </label>
              </th>
            <th mat-sort-header="userName">User Name</th>
            <th mat-sort-header="phone">Phone</th>
            <th mat-sort-header="email">email</th>
            <th mat-sort-header="role">Role</th>
            <th mat-sort-header="createdOn">Created On</th>
            <th mat-sort-header="status">Status</th>
            <th class="no-sort">Action</th>
          </tr>
        </thead>
        <tbody>
          @for (data of tableData; track data) {
            <tr>
              <td>
                  <label class="checkboxs">
                    <input type="checkbox" [(ngModel)]="data.isSelected">
                    <span class="checkmarks"></span>
                  </label>
                </td>
              <td>
                <div class="userimgname">
                  <a href="javascript:void(0);" class="userslist-img bg-img">
                    <img [src]="data.img" alt="product">
                  </a>
                  <div>
                    <a href="javascript:void(0);">{{data.userName}}</a>
                  </div>
                </div>
              </td>
              <td>{{data.phone}}</td>
              <td>{{data.email}}</td>
              <td>{{data.role}}</td>
              <td>{{data.createdOn}}</td>
              <td><span class="badge"
              [ngClass]="{'badge-linesuccess': data.status === 'Active', 'badge-linedanger': data.status === 'Inactive'}">{{data.status}}</span>
            </td>
            <td class="action-table-data">
              <div class="edit-delete-action">
                <a class="me-2 p-2 mb-0" href="javascript:void(0);">
                  <i class="feather icon-eye action-eye"></i>
                </a>
                <a class="me-2 p-2 mb-0" data-bs-toggle="modal" data-bs-target="#edit-units">
                  <i class="feather icon-edit feather-edit"></i>
                </a>
                <a class="me-2 confirm-text p-2 mb-0" href="javascript:void(0);" (click)=confirmColor()>
                  <i class="feather icon-trash-2 feather-trash-2"></i>
                </a>
              </div>
            </td>
          </tr>
        }
      </tbody>
    </table>
  </div>
  <app-custom-pagination></app-custom-pagination>
</div>
</div>
<!-- /product list -->

<!-- Add User -->
<div class="modal fade" id="add-units">
  <div class="modal-dialog modal-dialog-centered custom-modal-two">
    <div class="modal-content">
      <div class="page-wrapper-new p-0">
        <div class="content">
          <div class="modal-header border-0 custom-modal-header">
            <div class="page-title">
              <h4>Add User</h4>
            </div>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body custom-modal-body">
            <form>
              <div class="row">
                <div class="col-lg-12">
                  <div class="new-employee-field">
                    <span>Avatar</span>
                    <div class="profile-pic-upload mb-2">
                      <div class="profile-pic">
                        <span><i class="feather icon-plus-circle plus-down-add"></i> Profile
                      Photo</span>
                    </div>
                    <div class="input-blocks mb-0">
                      <div class="image-upload mb-0">
                        <input type="file">
                        <div class="image-uploads">
                          <h4>Change Image</h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="input-blocks">
                  <label>User Name</label>
                  <input type="text" class="form-control">
                </div>
              </div>
              <div class="col-lg-6">
                <div class="input-blocks">
                  <label>Phone</label>
                  <input type="text" class="form-control">
                </div>
              </div>

              <div class="col-lg-6">
                <div class="input-blocks">
                  <label>Email</label>
                  <input type="email" class="form-control">
                </div>
              </div>
              <div class="col-lg-6">
                <div class="input-blocks">
                  <label>Role</label>
                  <mat-select [(ngModel)]="selectedValue6" [ngModelOptions]="{standalone: true}" class="select"
                    placeholder="Choose">
                    <mat-option value="Choose">Choose</mat-option>
                    <mat-option value="Manager">Manager</mat-option>
                    <mat-option value="Admin">Admin</mat-option>
                  </mat-select>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="input-blocks">
                  <label>Password</label>
                  <div class="pass-group">
                    <input [type]="password[1] ? 'text' : 'password' " class="pass-input"
                      placeholder="Enter your password">
                      <span class="fas toggle-password" [ngClass]=" password[1] ? 'fa-eye' : 'fa-eye-slash'"
                      (click)="togglePassword(1)"></span>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="input-blocks">
                    <label>Confirm Password</label>
                    <div class="pass-group">
                      <input [type]="password[2] ? 'text' : 'password' " class="pass-input"
                        placeholder="Enter your password">
                        <span class="fas toggle-password" [ngClass]=" password[2] ? 'fa-eye' : 'fa-eye-slash'"
                        (click)="togglePassword(2)"></span>
                      </div>
                    </div>
                  </div>

                  <div class="col-lg-12">
                    <div class="mb-0 input-blocks">
                      <label class="form-label">Descriptions</label>
                      <textarea class="form-control mb-1">Type Message</textarea>
                      <p>Maximum 600 Characters</p>
                    </div>
                  </div>
                </div>
                <div class="modal-footer-btn">
                  <button type="button" class="btn btn-cancel me-2" data-bs-dismiss="modal">Cancel</button>
                  <button type="submit" class="btn btn-submit">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Add User -->

  <!-- Edit User -->
  <div class="modal fade" id="edit-units">
    <div class="modal-dialog modal-dialog-centered custom-modal-two">
      <div class="modal-content">
        <div class="page-wrapper-new p-0">
          <div class="content">
            <div class="modal-header border-0 custom-modal-header">
              <div class="page-title">
                <h4>Edit User</h4>
              </div>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body custom-modal-body">
              <form>
                <div class="row">
                  <div class="col-lg-12">
                    <div class="new-employee-field">
                      <span>Avatar</span>
                      <div class="profile-pic-upload edit-pic">
                        <div class="profile-pic">
                          <span><img src="assets/img/users/edit-user.jpg" class="user-editer" alt="User"></span>
                          <div class="close-img">
                            <i class="feather icon-x info-img"></i>
                          </div>
                        </div>
                        <div class="input-blocks mb-0">
                          <div class="image-upload mb-0">
                            <input type="file">
                            <div class="image-uploads">
                              <h4>Change Image</h4>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="input-blocks">
                      <label>User Name</label>
                      <input type="text" placeholder="Thomas">
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="input-blocks">
                      <label>Phone</label>
                      <input type="text" placeholder="+12163547758 ">
                    </div>
                  </div>

                  <div class="col-lg-6">
                    <div class="input-blocks">
                      <label>Email</label>
                      <input type="email" placeholder="thomas&#64;example.com">
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="input-blocks">
                      <label>Role</label>
                      <mat-select [(ngModel)]="selectedValue7" [ngModelOptions]="{standalone: true}" class="select"
                        placeholder="Choose">
                        <mat-option value="Admin">Admin</mat-option>
                        <mat-option value="Manager">Manager</mat-option>
                        <mat-option value="Store Keeper">Store Keeper</mat-option>
                      </mat-select>
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="input-blocks">
                      <label>Password</label>
                      <div class="pass-group">
                        <input [type]="password[3] ? 'text' : 'password' " class="pass-input"
                          placeholder="Enter your password">
                          <span class="fas toggle-password" [ngClass]=" password[3] ? 'fa-eye' : 'fa-eye-slash'"
                          (click)="togglePassword(3)"></span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="input-blocks">
                        <label>Confirm Password</label>
                        <div class="pass-group">
                          <input [type]="password[4] ? 'text' : 'password' " class="pass-input"
                            placeholder="Enter your password">
                            <span class="fas toggle-password" [ngClass]=" password[4] ? 'fa-eye' : 'fa-eye-slash'"
                            (click)="togglePassword(4)"></span>
                          </div>
                        </div>
                      </div>

                      <div class="col-lg-12">
                        <div class="mb-0 input-blocks">
                          <label class="form-label">Descriptions</label>
                          <textarea class="form-control mb-1"></textarea>
                          <p>Maximum 600 Characters</p>
                        </div>
                      </div>
                    </div>
                    <div class="modal-footer-btn">
                      <button type="button" class="btn btn-cancel me-2" data-bs-dismiss="modal">Cancel</button>
                      <button type="submit" class="btn btn-submit">Submit</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /Edit User -->
