// dreamspos_v2.0.6/react/template/src/feature-module/Reports/taxreport.jsx
import React, { useState } from "react";
import { Filter, Sliders } from "react-feather";
import { Link } from "react-router-dom";
import ImageWithBasePath from "../../core/img/imagewithbasebath";
import Select from "react-select";
import { Zap } from "react-feather/dist";
import { CreditCard } from "feather-icons-react/build/IconComponents";
import { Calendar } from "react-feather";
import DateRangePicker from "react-bootstrap-daterangepicker";
import Breadcrumbs from "../../core/breadcrumbs";

const TaxReport = () => {
  const [isFilterVisible, setIsFilterVisible] = useState(false);
  const [isFilterVisibleTwo, setIsFilterVisibleTwo] = useState(false);

  const toggleFilterVisibility = () => {
    setIsFilterVisible((prevVisibility) => !prevVisibility);
  };

  const toggleFilterVisibilityTwo = () => {
    setIsFilterVisibleTwo((prevVisibilityTwo) => !prevVisibilityTwo);
  };

  const options = [
    { value: "sortByDate", label: "Sort by Date" },
    { value: "140923", label: "14 09 23" },
    { value: "110923", label: "11 09 23" },
  ];

  const optionsTwo = [
    { value: "sortByDate", label: "Sort by Date" },
    { value: "140923", label: "14 09 23" },
    { value: "110923", label: "11 09 23" },
  ];

  const optionsCategory = [{ value: "Computers", label: "Computers" }];

  const optionsPaymentMethod = [
    { value: "Complete", label: "Complete" },
    { value: "Inprogress", label: "Inprogress" },
  ];
  const initialSettings = {
    endDate: new Date("2020-08-11T12:30:00.000Z"),
    ranges: {
      "Last 30 Days": [
        new Date("2020-07-12T04:57:17.076Z"),
        new Date("2020-08-10T04:57:17.076Z"),
      ],
      "Last 7 Days": [
        new Date("2020-08-04T04:57:17.076Z"),
        new Date("2020-08-10T04:57:17.076Z"),
      ],
      "Last Month": [
        new Date("2020-06-30T18:30:00.000Z"),
        new Date("2020-07-31T18:29:59.999Z"),
      ],
      "This Month": [
        new Date("2020-07-31T18:30:00.000Z"),
        new Date("2020-08-31T18:29:59.999Z"),
      ],
      Today: [
        new Date("2020-08-10T04:57:17.076Z"),
        new Date("2020-08-10T04:57:17.076Z"),
      ],
      Yesterday: [
        new Date("2020-08-09T04:57:17.076Z"),
        new Date("2020-08-09T04:57:17.076Z"),
      ],
    },
    startDate: new Date("2020-08-04T04:57:17.076Z"), // Set "Last 7 Days" as default
    timePicker: false,
  };
  return (
    <div className="page-wrapper">
      <div className="content">
        <Breadcrumbs maintitle="Tax Report" subtitle="Manage Your Tax Report" />
        {/* /product list */}
        <div className="card table-list-card">
          <div className="card-body">
            <div className="tabs-set">
              <ul className="nav nav-tabs" id="myTab" role="tablist">
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link active"
                    id="purchase-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#purchase2"
                    type="button"
                    role="tab"
                    aria-controls="purchase2"
                    aria-selected="true"
                  >
                    Purchase Tax Report
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link"
                    id="sales-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#sales2"
                    type="button"
                    role="tab"
                    aria-controls="sales2"
                    aria-selected="false"
                  >
                    Sales Tax Report
                  </button>
                </li>
              </ul>
              <div className="tab-content" id="myTabContent">
                <div
                  className="tab-pane fade show active"
                  id="purchase2"
                  role="tabpanel"
                  aria-labelledby="purchase-tab"
                >
                  <div className="table-top">
                    <div className="search-set">
                      <div className="search-input">
                        <input
                          type="text"
                          placeholder="Search"
                          className="form-control form-control-sm formsearch"
                        />
                        <Link to className="btn btn-searchset">
                          <i data-feather="search" className="feather-search" />
                        </Link>
                      </div>
                    </div>
                    <div className="search-path">
                      <Link
                        className={`btn btn-filter ${
                          isFilterVisible ? "setclose" : ""
                        }`}
                        id="filter_search"
                      >
                        <Filter
                          className="filter-icon"
                          onClick={toggleFilterVisibility}
                        />
                        <span onClick={toggleFilterVisibility}>
                          <ImageWithBasePath
                            src="assets/img/icons/closes.svg"
                            alt="img"
                          />
                        </span>
                      </Link>
                    </div>
                    <div className="form-sort stylewidth">
                      <Sliders className="info-img" />

                      <Select
                        className="select "
                        options={options}
                        placeholder="Sort by Date"
                      />
                    </div>
                  </div>
                  {/* /Filter */}
                  <div
                    className={`card${isFilterVisible ? " visible" : ""}`}
                    id="filter_inputs"
                    style={{ display: isFilterVisible ? "block" : "none" }}
                  >
                    <div className="card-body pb-0">
                      <div className="row">
                        <div className="col-lg-2 col-sm-6 col-12">
                          <div className="input-blocks">
                            <Zap className="info-img" />
                            <Select
                              className="select"
                              options={optionsCategory}
                              placeholder="Choose Category"
                            />
                          </div>
                        </div>
                        <div className="col-lg-2 col-sm-6 col-12">
                          <div className="input-blocks">
                            <CreditCard className="info-img" />
                            <Select
                              className="select"
                              options={optionsPaymentMethod}
                              placeholder="Payment Method"
                            />
                          </div>
                        </div>
                        <div className="col-lg-3 col-sm-6 col-12">
                          <div className="input-blocks">
                            <div className="position-relative daterange-wraper">
                              <Calendar className="feather-14 info-img" />

                              <DateRangePicker
                                initialSettings={initialSettings}
                              >
                                <input
                                  className="form-control col-4 input-range"
                                  type="text"
                                  style={{ border: "none" }}
                                />
                              </DateRangePicker>
                            </div>
                          </div>
                        </div>
                        <div className="col-lg-3 col-sm-6 col-12 ms-auto">
                          <div className="input-blocks">
                            <Link className="btn btn-filters ms-auto">
                              {" "}
                              <i
                                data-feather="search"
                                className="feather-search"
                              />{" "}
                              Search{" "}
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Filter */}
                  <div className="table-responsive">
                    <table className="table datanew">
                      <thead>
                        <tr>
                          <th>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </th>
                          <th>Supplier</th>
                          <th>Date</th>
                          <th>Ref No</th>
                          <th>Total Amount</th>
                          <th>Payment Method</th>
                          <th>Discount</th>
                          <th>Tax Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td>Lavi</td>
                          <td>12 Jul 2023</td>
                          <td className="ref-number">#4237300</td>
                          <td>$30,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/pay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>10</td>
                          <td>$457</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td>Anthony</td>
                          <td>18 Aug 2023</td>
                          <td className="ref-number">#5628954</td>
                          <td>$45,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/stripe.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>12</td>
                          <td>$265</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td>Colleen</td>
                          <td>27 Aug 2023</td>
                          <td className="ref-number">#8745239</td>
                          <td>$26,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/razorpay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>08</td>
                          <td>$980</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td>Victor</td>
                          <td>05 Sep 2023</td>
                          <td className="ref-number">#9814586</td>
                          <td>$18,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/pay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>15</td>
                          <td>$561</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td>Tracy</td>
                          <td>23 Sep 2023</td>
                          <td className="ref-number">#7590325</td>
                          <td>$52,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/pay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>20</td>
                          <td>$382</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div
                  className="tab-pane fade"
                  id="sales2"
                  role="tabpanel"
                  aria-labelledby="sales-tab"
                >
                  <div className="table-top">
                    <div className="search-set">
                      <div className="search-input">
                        <input
                          type="text"
                          placeholder="Search"
                          className="form-control form-control-sm formsearch"
                        />
                        <Link to className="btn btn-searchset">
                          <i data-feather="search" className="feather-search" />
                        </Link>
                      </div>
                    </div>
                    <div className="search-path">
                      <Link
                        className={`btn btn-filter ${
                          isFilterVisibleTwo ? "setclose" : ""
                        }`}
                        id="filter_search"
                      >
                        <Filter
                          className="filter-icon"
                          onClick={toggleFilterVisibilityTwo}
                        />
                        <span onClick={toggleFilterVisibilityTwo}>
                          <ImageWithBasePath
                            src="assets/img/icons/closes.svg"
                            alt="img"
                          />
                        </span>
                      </Link>
                    </div>
                    <div className="form-sort stylewidth">
                      <Sliders className="info-img" />

                      <Select
                        className="select"
                        options={optionsTwo}
                        placeholder="Sort by Date"
                      />
                    </div>
                  </div>
                  {/* /Filter */}
                  <div
                    className={`card${isFilterVisibleTwo ? " visible" : ""}`}
                    id="filter_inputs2"
                    style={{ display: isFilterVisibleTwo ? "block" : "none" }}
                  >
                    <div className="card-body pb-0">
                      <div className="row">
                        <div className="col-lg-2 col-sm-6 col-12">
                          <div className="input-blocks">
                            <Zap className="info-img" />
                            <Select
                              className="select"
                              options={optionsCategory}
                              placeholder="Choose Category"
                            />
                          </div>
                        </div>
                        <div className="col-lg-2 col-sm-6 col-12">
                          <div className="input-blocks">
                            <CreditCard className="info-img" />
                            <Select
                              className="select"
                              options={optionsPaymentMethod}
                              placeholder="Payment Method"
                            />
                          </div>
                        </div>
                        <div className="col-lg-3 col-sm-6 col-12">
                          <div className="input-blocks">
                            <div className="position-relative daterange-wraper">
                              <Calendar className="feather-14 info-img" />

                              <DateRangePicker
                                initialSettings={initialSettings}
                              >
                                <input
                                  className="form-control col-4 input-range"
                                  type="text"
                                  style={{ border: "none" }}
                                />
                              </DateRangePicker>
                            </div>
                          </div>
                        </div>
                        <div className="col-lg-3 col-sm-6 col-12 ms-auto">
                          <div className="input-blocks">
                            <Link className="btn btn-filters ms-auto">
                              {" "}
                              <i
                                data-feather="search"
                                className="feather-search"
                              />{" "}
                              Search{" "}
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Filter */}
                  <div className="table-responsive">
                    <table className="table datanew">
                      <thead>
                        <tr>
                          <th>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </th>
                          <th>Customer</th>
                          <th>Date</th>
                          <th>Invoice Number</th>
                          <th>Total Amount</th>
                          <th>Payment Method</th>
                          <th>Discount</th>
                          <th>Tax Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td className="userimgname">
                            <Link to="#" className="product-img">
                              <ImageWithBasePath
                                src="assets/img/users/user-01.jpg"
                                alt="product"
                              />
                            </Link>
                            <Link to="#">Mitchum Daniel</Link>
                          </td>
                          <td>12 Jul 2023</td>
                          <td className="ref-number">INV4237300</td>
                          <td>$30,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/pay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>10</td>
                          <td>$457</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td className="userimgname">
                            <Link to="#" className="product-img">
                              <ImageWithBasePath
                                src="assets/img/users/user-02.jpg"
                                alt="product"
                              />
                            </Link>
                            <Link to="#">Susan Lopez</Link>
                          </td>
                          <td>04 Aug 2023</td>
                          <td className="ref-number">INV5385083</td>
                          <td>$27,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/stripe.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>08</td>
                          <td>$382</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td className="userimgname">
                            <Link to="#" className="product-img">
                              <ImageWithBasePath
                                src="assets/img/users/user-03.jpg"
                                alt="product"
                              />
                            </Link>
                            <Link to="#">Robert</Link>
                          </td>
                          <td>25 Aug 2023</td>
                          <td className="ref-number">INV7609368</td>
                          <td>$45,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/razorpay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>15</td>
                          <td>$649</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td className="userimgname">
                            <Link to="#" className="product-img">
                              <ImageWithBasePath
                                src="assets/img/users/user-04.jpg"
                                alt="product"
                              />
                            </Link>
                            <Link to="#">Russell Belle</Link>
                          </td>
                          <td>16 Sep 2023</td>
                          <td className="ref-number">INV2750916</td>
                          <td>$18,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/pay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>12</td>
                          <td>$104</td>
                        </tr>
                        <tr>
                          <td>
                            <label className="checkboxs">
                              <input type="checkbox" />
                              <span className="checkmarks" />
                            </label>
                          </td>
                          <td className="userimgname">
                            <Link to="#" className="product-img">
                              <ImageWithBasePath
                                src="assets/img/users/user-05.jpg"
                                alt="product"
                              />
                            </Link>
                            <Link to="#">Edward Muniz</Link>
                          </td>
                          <td>28 Oct 2023</td>
                          <td className="ref-number">INV3478305</td>
                          <td>$22,000</td>
                          <td className="payment-info">
                            <Link to="#">
                              {" "}
                              <ImageWithBasePath
                                src="assets/img/icons/pay.svg"
                                alt="Pay"
                              />{" "}
                            </Link>
                          </td>
                          <td>20</td>
                          <td>$290</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* /product list */}
      </div>
    </div>
  );
};

export default TaxReport;

// dreamspos_v2.0.6/vue/template/src/views/pages/reports/tax-report/tax-report.vue
<template>
  <layout-header></layout-header>
  <layout-sidebar></layout-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="page-header justify-content-between">
        <div class="page-title">
          <h4>Tax Reports</h4>
          <h6>Manage your Tax Reports</h6>
        </div>
        <ul class="table-top-head">
          <li>
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Pdf"
              ><img src="@/assets/img/icons/pdf.svg" alt="img"
            /></a>
          </li>
          <li>
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Excel"
              ><img src="@/assets/img/icons/excel.svg" alt="img"
            /></a>
          </li>
          <li>
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Print"
              ><i data-feather="printer" class="feather-rotate-ccw"></i
            ></a>
          </li>
          <li>
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Refresh"
              ><i data-feather="rotate-ccw" class="feather-rotate-ccw"></i
            ></a>
          </li>
          <li>
            <a
              ref="collapseHeader"
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Collapse"
              @click="toggleCollapse"
            >
              <i data-feather="chevron-up" class="feather-chevron-up"></i>
            </a>
          </li>
        </ul>
      </div>

      <!-- /product list -->
      <div class="card table-list-card">
        <div class="card-body">
          <div class="tabs-set">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <button
                  class="nav-link active"
                  id="purchase-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#purchase2"
                  type="button"
                  role="tab"
                  aria-controls="purchase2"
                  aria-selected="true"
                >
                  Purchase Tax Report
                </button>
              </li>
              <li class="nav-item" role="presentation">
                <button
                  class="nav-link"
                  id="sales-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#sales2"
                  type="button"
                  role="tab"
                  aria-controls="sales2"
                  aria-selected="false"
                >
                  Sales Tax Report
                </button>
              </li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div
                class="tab-pane fade show active"
                id="purchase2"
                role="tabpanel"
                aria-labelledby="purchase-tab"
              >
                <div class="table-top">
                  <div class="search-set">
                    <div class="search-input">
                      <input type="text" placeholder="Search" class="dark-input" />
                      <a href="" class="btn btn-searchset"
                        ><i data-feather="search" class="feather-search"></i
                      ></a>
                    </div>
                  </div>
                  <div class="search-path">
                    <div class="d-flex align-items-center">
                      <a
                        class="btn btn-filter"
                        id="filter_search"
                        v-on:click="filter = !filter"
                        :class="{ setclose: filter }"
                      >
                        <vue-feather type="filter" class="filter-icon"></vue-feather>
                        <span><img src="@/assets/img/icons/closes.svg" alt="img" /></span>
                      </a>
                      <a href="" class="me-3 layout-box"
                        ><vue-feather type="layout" class="layout"></vue-feather
                      ></a>
                    </div>
                  </div>
                  <div class="form-sort">
                    <vue-feather type="sliders" class="info-img"></vue-feather>
                    <vue-select
                      :options="TaxSort"
                      id="taxsort"
                      placeholder="Sort by Date"
                    />
                  </div>
                </div>
                <!-- /Filter -->
                <div
                  class="card"
                  :style="{ display: filter ? 'block' : 'none' }"
                  id="filter_inputs"
                >
                  <div class="card-body pb-0">
                    <div class="row">
                      <div class="col-lg-2 col-sm-6 col-12">
                        <div class="input-blocks">
                          <vue-feather type="zap" class="info-img"></vue-feather>
                          <vue-select
                            :options="TaxCat"
                            id="taxcat"
                            placeholder="Choose Category"
                          />
                        </div>
                      </div>
                      <div class="col-lg-2 col-sm-6 col-12">
                        <div class="input-blocks">
                          <vue-feather type="credit-card" class="info-img"></vue-feather>
                          <vue-select
                            :options="PaymentMethodTax"
                            id="paymentmethodtax"
                            placeholder="Payment Method"
                          />
                        </div>
                      </div>
                      <div class="col-lg-3 col-sm-6 col-12">
                        <div class="input-blocks">
                          <div class="position-relative daterange-wraper">
                            <input
                              type="text"
                              class="form-control date-range bookingrange"
                              ref="dateRangeInput"
                              placeholder="From Date - To Date"
                              name="datetimes"
                            />
                            <vue-feather
                              type="calendar"
                              class="feather-14 info-img"
                            ></vue-feather>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-3 col-sm-6 col-12 ms-auto">
                        <div class="input-blocks">
                          <a class="btn btn-filters ms-auto">
                            <i data-feather="search" class="feather-search"></i> Search
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /Filter -->
                <div class="table-responsive">
                  <a-table
                    class="table datanew"
                    :columns="columns"
                    :data-source="data"
                    :row-selection="{}"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'RefNo'">
                        <td class="ref-number">{{ record.RefNo }}</td>
                      </template>
                      <template v-else-if="column.key === 'PaymentMethod'">
                        <div class="payment-info">
                          <a href="javascript:void(0);">
                            <img
                              :src="require(`@/assets/img/icons/${record.PaymentMethod}`)"
                              alt="Pay"
                            />
                          </a>
                        </div>
                      </template>
                    </template>
                  </a-table>
                </div>
              </div>
              <salestax-report></salestax-report>
            </div>
          </div>
        </div>
      </div>
      <!-- /product list -->
    </div>
  </div>
</template>
<script>
const columns = [
  {
    title: "Supplier",
    dataIndex: "Supplier",
    key: "Supplier",
    sorter: {
      compare: (a, b) => {
        a = a.Supplier.toLowerCase();
        b = b.Supplier.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Date",
    dataIndex: "Date",
    sorter: {
      compare: (a, b) => {
        a = a.Date.toLowerCase();
        b = b.Date.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Ref No",
    dataIndex: "RefNo",
    key: "RefNo",
    sorter: {
      compare: (a, b) => {
        a = a.RefNo.toLowerCase();
        b = b.RefNo.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Total Amount",
    dataIndex: "TotalAmount",
    key: "TotalAmount",
    sorter: {
      compare: (a, b) => {
        a = a.TotalAmount.toLowerCase();
        b = b.TotalAmount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Payment Method",
    dataIndex: "PaymentMethod",
    key: "PaymentMethod",
    sorter: {
      compare: (a, b) => {
        a = a.PaymentMethod.toLowerCase();
        b = b.PaymentMethod.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Discount",
    dataIndex: "Discount",
    sorter: {
      compare: (a, b) => {
        a = a.Discount.toLowerCase();
        b = b.Discount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Tax Amount",
    dataIndex: "TaxAmount",
    sorter: {
      compare: (a, b) => {
        a = a.TaxAmount.toLowerCase();
        b = b.TaxAmount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
];
const data = [
  {
    Supplier: "Lavi",
    Date: "12 Jul 2023",
    RefNo: "#4237300",
    TotalAmount: "$30,000",
    PaymentMethod: "pay.svg",
    Discount: "10",
    TaxAmount: "$457",
  },
  {
    Supplier: "Anthony",
    Date: "18 Aug 2023",
    RefNo: "#5628954",
    TotalAmount: "$45,000",
    PaymentMethod: "stripe.svg",
    Discount: "12",
    TaxAmount: "$265",
  },
  {
    Supplier: "Colleen",
    Date: "27 Aug 2023",
    RefNo: "#8745239",
    TotalAmount: "$26,000",
    PaymentMethod: "razorpay.svg",
    Discount: "8",
    TaxAmount: "$980",
  },
  {
    Supplier: "Victor",
    Date: "05 Sep 2023",
    RefNo: "#9814586",
    TotalAmount: "$18,000",
    PaymentMethod: "pay.svg",
    Discount: "15",
    TaxAmount: "$561",
  },
  {
    Supplier: "Tracy",
    Date: "23 Sep 2023",
    RefNo: "#7590325",
    TotalAmount: "$52,000",
    PaymentMethod: "pay.svg",
    Discount: "20",
    TaxAmount: "$382",
  },
];
import "daterangepicker/daterangepicker.css";
import "daterangepicker/daterangepicker.js";
import { ref } from "vue";
import { onMounted } from "vue";
import moment from "moment";
import DateRangePicker from "daterangepicker";
export default {
  data() {
    return {
      filter: false,
      TaxSort: ["Sort by Date", "Oldest"],
      TaxCat: ["Choose Category", "Computers"],
      PaymentMethodTax: ["Payment Method", "Complete", "Inprogress"],
      data,
      columns,
    };
  },
  setup() {
    const dateRangeInput = ref(null);
    onMounted(() => {
      if (dateRangeInput.value) {
        const start = moment().subtract(6, "days");
        const end = moment();

        function booking_range(start, end) {
          return start.format("M/D/YYYY") + " - " + end.format("M/D/YYYY");
        }

        new DateRangePicker(
          dateRangeInput.value,
          {
            startDate: start,
            endDate: end,
            ranges: {},
          },
          booking_range
        );

        booking_range(start, end);
      }
    });
    return {
      dateRangeInput,
    };
  },
  methods: {
    booking_range(start, end) {
      return start.format("M/D/YYYY") + " - " + end.format("M/D/YYYY");
    },
    toggleCollapse() {
      const collapseHeader = this.$refs.collapseHeader;

      if (collapseHeader) {
        collapseHeader.classList.toggle("active");
        document.body.classList.toggle("header-collapse");
      }
    },
  },
};
</script>
